// AnalysisTools.idl : type library source for AnalysisTools.dll
// This file will be processed by the MIDL compiler to produce the
// type library (AnalysisTools.tlb).

#include "olectl.h"
[uuid(8E069405-7078-499A-A844-5DB9B00C9252), version(1.0)]
library AnalysisTools
{
  importlib("stdole32.tlb");
  importlib("stdole2.tlb");
  //  Primary dispatch interface for AnalysisObject

  [uuid(EA4DEC31-FC91-4FB7-8819-0DCC67CB5E3A)]
  dispinterface IAnalysisObject
  {
    properties:
    methods:
      [id(1), helpstring("IsAnalysisMesh")] VARIANT IsAnalysisMesh(VARIANT vaObject);
      [id(2), helpstring("AddAnalysisMesh")] VARIANT AddAnalysisMesh(VARIANT vaVertices, VARIANT vaFaces, VARIANT vaData);
      [id(3), helpstring("AnalysisMeshData")] VARIANT AnalysisMeshData(VARIANT vaObject,[optional]VARIANT vaData);
      [id(4), helpstring("AnalysisMeshDisplayRange")] VARIANT AnalysisMeshDisplayRange(VARIANT vaObject,[optional]VARIANT vaRange);
      [id(5), helpstring("AnalysisMeshDataRange")] VARIANT AnalysisMeshDataRange(VARIANT vaObject);
  };

  //  Class information for AnalysisObject

  [uuid(264A3329-46DF-4B99-A63F-84F7470E10F0)]
  coclass AnalysisObject
  {
    [default] dispinterface IAnalysisObject;
  };
};
